### PR TITLE
Motmetrics evaluation added

### PR DESCRIPTION
**Pull request by samyhocine**
Hi,

It's a pull request :) I've added a small glue logic to evalute deepsort_pytorch.

I've tested it on the MOT16 training dataset (to do a local evaluation).
I was surprised to find out that the results are below the original DeepSort:

deepsort_pytorch_mot16train_res

The overall MOTA is 30.1%

I've launched a visual test on a video with moving people and static people and during almost 80% of the time, bboxes are blinking (it's not a 50/50 ratio, it's seems random). The detection seems to be completely unstable.

Because deepsort_pytorch works on a video as an input instead of frames (no option to choose between the two), I had to, for each img1 folder in MOT16/train/MOT*, convert the frames into a video using this command: `ffmpeg -f image2 -i %06d.jpg -c:v copy video.mp4`

In the end the dataset folder architecture shall be this one:

data/dataset/MOT16/MOT16-02/

- /det/det.txt
- /gt/gt.txt
- /img1/*.jpg
- /video/video.mp4
- seqinfo.ini

The dataset (without videos) can be downloaded from [here ](https://motchallenge.net/data/MOT16.zip)<-

To test it, just launch:

`python yolov3_deepsort_eval.py`

Best regards ;)

Samy Hocine

### CODE REVIEW

**Comment by ZQPei** [comment]
Thanks for your contribution!
Yes, the results of this repo are below the original DeepSort, because the model is not well trained and the origin model in DeepSort is trained using tensorflow.
I will find some time to fix this problem.
BTW, can you add the instruction of your contribution to `README.md` if you don't mind?
Thanks anyway.

**Comment by ZQPei** [comment]
One reason is that the detection of pedestrian result is not that good.

**Comment by antoniolq** [comment]
Yes, I tested it on mot16 by Matlab, this is my result:
```
 ********************* Your MOT16 Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 32.2 53.8 22.9| 35.8  83.9  1.43|  517  72  207  228|  7580 70934   606  1670|  28.3  70.9  28.9 
```
some metrics are a little different with **samyhocine**, I want to retrain or replace the detection model to get a better result, can you provide the train code of YoloV3 or some steps about how to replace the detection model? 
Thank you very much!

**Comment by ZQPei** [comment]
It is not too difficult to replace the detection model.
Just replace the YOLOv3 in `detector`, and remember to keep the output of your custom detector as the same as I did.
You can tell me if you encount any problems.

**Comment by antoniolq** [comment]
Thank you very much, I will try it.

**Comment by antoniolq** [comment]
I replaced it with efficientdet, but the results is worse then before......

**Pull request merged**
