### PR TITLE
[feature] support YOLOv5 and fix bugs

### PR DESCRIPTION
**Pull request by cjliu01**
add some contents about YOLOv5 detector, tracking results showing and modify some errors about kalman_filter.py, detector.YOLOv3.weight.yolo_utils.py(This eliminates the need for compiling NMS operators).

### CODE REVIEW

**Comment by cjliu01** [comment]
later modifications to READMD.md will be uploaded, as well as updates to the appearance feature extraction network.

**Comment by ZQPei** [comment]
Thanks a lot for your contribution!
This PR title is a bit confusing. It will be much better to use a more descriptive title instead of ambiguous words like "some".

**Comment by cjliu01** [comment]
tracking 
1. Added resnet network to the appearance feature extraction network in the deep folder
2. modified the NMS bug in the preprocessing.py and the updated covariance calculation bug in the kalmen_filter.py in the sort folder
detecting
1. Added YOLOv5 detector, aligned interface, and added YOLOv5 related yaml configuration files
2. The training, evaluation and prediction in the original YOLOv5 were deleted
deepsort
1. Added tracking target category, which can display both category and tracking ID simultaneously

**Comment by ZQPei** [comment]
> tracking
> 
> 1. Added resnet network to the appearance feature extraction network in the deep folder
> 2. modified the NMS bug in the preprocessing.py and the updated covariance calculation bug in the kalmen_filter.py in the sort folder
>    detecting
> 3. Added YOLOv5 detector, aligned interface, and added YOLOv5 related yaml configuration files
> 4. The training, evaluation and prediction in the original YOLOv5 were deleted
>    deepsort
> 5. Added tracking target category, which can display both category and tracking ID simultaneously

Great job! Will you update the title as well, please?

**Comment by ZQPei** [comment]
> later modifications to READMD.md will be uploaded, as well as updates to the appearance feature extraction network.

I assume these commits will be uploaded soon, correct?
This pull request will be merged once the remaining is ready.

**Comment by cjliu01** [comment]
> > tracking
> > 
> > 1. Added resnet network to the appearance feature extraction network in the deep folder
> > 2. modified the NMS bug in the preprocessing.py and the updated covariance calculation bug in the kalmen_filter.py in the sort folder
> >    detecting
> > 3. Added YOLOv5 detector, aligned interface, and added YOLOv5 related yaml configuration files
> > 4. The training, evaluation and prediction in the original YOLOv5 were deleted
> >    deepsort
> > 5. Added tracking target category, which can display both category and tracking ID simultaneously
> 
> Great job! Will you update the title as well, please?

Is there any standard for naming titles

**Comment by cjliu01** [comment]
> > later modifications to READMD.md will be uploaded, as well as updates to the appearance feature extraction network.
> 
> I assume these commits will be uploaded soon, correct? This pull request will be merged once the remaining is ready.

updated on the appearance feature extraction network and README.md

**Comment by ZQPei** [comment]
Hi, is it convenient for you to solve the conflicts that introduced by your PR with the previous one (https://github.com/ZQPei/deep_sort_pytorch/pull/262)?

**Comment by cjliu01** [comment]
I will try to merge MaskRCNN into the main branch, but it will take some time.

**Pull request merged**
